import { app } from 'electron'
import { spawn } from 'node:child_process'
import { closeSync, existsSync, openSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { BREW_UPGRADE_COMMAND } from '../shared/ipc-types'
import type { UpdateInstallResult } from '../shared/ipc-types'

const CASK_TOKEN = 'simpleedit'
const CASK_FULL_NAME = 'pago/simpleedit/simpleedit'

// Must match `appId` in electron-builder.yml — `open -b` needs it to relaunch.
const BUNDLE_ID = 'com.simpleedit.app'

// Apple silicon and Intel Homebrew prefixes. Every lookup here has to be
// absolute: an app launched from Finder inherits a minimal PATH with no brew on
// it, so `brew` alone would simply not resolve.
const HOMEBREW_PREFIXES = ['/opt/homebrew', '/usr/local']

/**
 * Whether `brew` owns this copy of the app.
 *
 * A cask install moves SimpleEdit.app into /Applications but leaves a
 * `Caskroom/simpleedit/<version>` directory behind, so a directory matching the
 * running version is the cheapest reliable signal — no shelling out to `brew`,
 * which isn't on the PATH here. Matching on the version rather than the bare
 * cask directory also means a copy the user later replaced by hand stops
 * counting as Homebrew-managed.
 *
 * The `isPackaged` guard matters beyond correctness: without it, a developer who
 * has the cask installed at the version in package.json would see `pnpm dev` and
 * the e2e suite take the Homebrew path.
 */
export function isHomebrewManaged(): boolean {
  if (process.platform !== 'darwin' || !app.isPackaged) return false
  return HOMEBREW_PREFIXES.some((prefix) =>
    existsSync(join(prefix, 'Caskroom', CASK_TOKEN, app.getVersion()))
  )
}

export function findBrewBinary(): string | null {
  for (const prefix of HOMEBREW_PREFIXES) {
    const candidate = join(prefix, 'bin', 'brew')
    if (existsSync(candidate)) return candidate
  }
  return null
}

export function upgradeLogPath(): string {
  return join(app.getPath('userData'), 'homebrew-update.log')
}

function resultPath(): string {
  return join(app.getPath('userData'), 'homebrew-update.json')
}

function scriptPath(): string {
  return join(app.getPath('userData'), 'homebrew-update.sh')
}

/** `.../SimpleEdit.app/Contents/MacOS/SimpleEdit` → `.../SimpleEdit.app` */
function appBundlePath(): string {
  return join(app.getPath('exe'), '..', '..', '..')
}

export interface HomebrewUpgradeResult {
  ok: boolean
  stage: string
  version: string
  detail: string
}

/**
 * The helper that actually performs the upgrade.
 *
 * It runs detached and only starts once the app has exited, which is the whole
 * point: `brew upgrade` run from a terminal *inside* SimpleEdit is a descendant
 * of the bundle being replaced, so quitting the app (`before-quit` →
 * `killAllTerminals`) would kill brew mid-upgrade — after Homebrew has moved the
 * old bundle to its backup and before the new one is in place.
 *
 * Exported so the tests can run the real thing against a stub `brew` — a bug in
 * here would only ever show up during an actual upgrade, which is the worst
 * possible time to find out.
 */
export const UPGRADE_SCRIPT = `#!/bin/sh
# Generated by SimpleEdit (src/main/homebrew.ts). Do not edit; it is rewritten on
# every update attempt.
#
# $1 pid to wait for   $2 brew binary  $3 cask   $4 result json
# $5 app bundle path   $6 bundle id    $7 target version
set -u

APP_PID="$1"; BREW="$2"; CASK="$3"; RESULT="$4"
APP="$5"; BUNDLE_ID="$6"; VERSION="$7"

write_result() {
  printf '{"ok":%s,"stage":"%s","version":"%s","detail":"%s"}\\n' \\
    "$1" "$2" "$VERSION" "$3" > "$RESULT"
}

echo "=== SimpleEdit Homebrew upgrade to $VERSION ==="
date

# Wait for the instance that asked for this. Bounded — if it never exits we must
# not upgrade underneath it. The bound is in half-seconds and overridable only so
# the tests do not have to burn a real minute proving the timeout works.
max_wait="\${SIMPLEEDIT_UPGRADE_MAX_WAIT:-120}"
waited=0
while kill -0 "$APP_PID" 2>/dev/null; do
  waited=$((waited + 1))
  if [ "$waited" -gt "$max_wait" ]; then
    echo "SimpleEdit (pid $APP_PID) still running after $((max_wait / 2))s; aborting."
    write_result false wait "SimpleEdit did not quit."
    exit 1
  fi
  sleep 0.5
done
echo "app exited after $((waited / 2))s"

# And make sure it was not reopened in the meantime. Upgrading under a live
# instance is exactly what this script exists to avoid. The pattern includes
# /Contents/MacOS/ so it cannot match this script's own argv.
#
# Only exit 1 means "nothing matched". 2 is a pattern pgrep could not compile
# (the bundle path is used as an extended regex, so a path containing regex
# metacharacters lands here), 3 an internal error, 127 no pgrep on PATH. In none
# of those did pgrep look and find nothing — treating them as "clear" is how you
# get brew replacing the bundle under a running app, which is the one outcome
# this script exists to prevent. stderr goes to the log rather than /dev/null so
# the reason is recoverable afterwards.
pgrep -f "$APP/Contents/MacOS/" >/dev/null
pgrep_status=$?
case "$pgrep_status" in
  0)
    echo "another SimpleEdit instance is running; aborting."
    write_result false relaunched "SimpleEdit was reopened before the update could run."
    exit 1
    ;;
  1) ;;
  *)
    echo "could not check for a running instance (pgrep exited $pgrep_status); aborting."
    write_result false guard "Could not confirm SimpleEdit had quit, so the update was not started."
    exit 1
    ;;
esac

# stdin from /dev/null so that a sudo prompt fails immediately rather than
# hanging forever in a job with no terminal to answer it.
echo "running: $BREW upgrade --cask $CASK"
HOMEBREW_NO_AUTO_UPDATE=1 "$BREW" upgrade --cask "$CASK" </dev/null &
brew_pid=$!

# Backstop: a wedged download must not leave the user with no app and no reason.
# The timeout is in seconds, overridable only so the tests do not have to wedge
# for half an hour to prove it fires.
#
# The sleep is a child of the watchdog subshell, and killing a subshell does not
# touch its children — so the watchdog has to wait on the sleep and pass the
# signal down, or every upgrade leaves a stray sleep orphaned to launchd for the
# rest of the half hour, still holding this log's file descriptor open.
upgrade_timeout="\${SIMPLEEDIT_UPGRADE_TIMEOUT:-1800}"
( sleep_pid=''
  trap '[ -n "$sleep_pid" ] && kill "$sleep_pid" 2>/dev/null; exit 0' TERM
  sleep "$upgrade_timeout" &
  sleep_pid=$!
  wait "$sleep_pid" || exit 0
  if kill -0 "$brew_pid" 2>/dev/null; then
    echo "brew still running after \${upgrade_timeout}s; terminating."
    kill -TERM "$brew_pid" 2>/dev/null
  fi ) &
watchdog_pid=$!

wait "$brew_pid"
status=$?
kill "$watchdog_pid" 2>/dev/null

echo "brew exited with status $status"
if [ "$status" -eq 0 ]; then
  write_result true done ""
else
  write_result false upgrade "brew exited with status $status"
fi

# Relaunch either way: the user quit expecting to come back, and on a failed
# upgrade Homebrew restores the previous bundle from its backup.
open "$APP" || open -b "$BUNDLE_ID"
echo "relaunch requested"
date
`

/**
 * Write the helper out and start it detached, so it outlives the app it is about
 * to replace. The caller is expected to quit immediately afterwards.
 */
export function startHomebrewUpgrade(version: string): UpdateInstallResult {
  const brew = findBrewBinary()
  if (!brew) {
    return {
      ok: false,
      error: `Could not find brew in ${HOMEBREW_PREFIXES.join(' or ')}. Run \`${BREW_UPGRADE_COMMAND}\` yourself.`
    }
  }

  const script = scriptPath()
  const log = upgradeLogPath()

  try {
    writeFileSync(script, UPGRADE_SCRIPT, { mode: 0o700 })
    // A stale result from a previous attempt would be reported as this one's.
    rmSync(resultPath(), { force: true })
  } catch (err) {
    return { ok: false, error: `Could not prepare the update helper: ${asMessage(err)}` }
  }

  // Truncate rather than append: the log describes the most recent attempt, and
  // nothing prunes it otherwise.
  let logFd: number
  try {
    logFd = openSync(log, 'w')
  } catch (err) {
    return { ok: false, error: `Could not open the update log: ${asMessage(err)}` }
  }

  try {
    const child = spawn(
      '/bin/sh',
      [
        script,
        String(process.pid),
        brew,
        CASK_FULL_NAME,
        resultPath(),
        appBundlePath(),
        BUNDLE_ID,
        version
      ],
      // detached gives the helper its own session, so it survives both our exit
      // and the process-group signals that take the PTY children down with us.
      { detached: true, stdio: ['ignore', logFd, logFd] }
    )
    child.unref()
    return { ok: true }
  } catch (err) {
    return { ok: false, error: `Could not start the update helper: ${asMessage(err)}` }
  } finally {
    closeSync(logFd)
  }
}

/**
 * Read and clear the result a previous detached upgrade left behind. Consumed
 * either way, so a one-off failure cannot nag on every launch.
 */
export function takeUpgradeResult(): HomebrewUpgradeResult | null {
  const path = resultPath()
  if (!existsSync(path)) return null

  let raw: string
  try {
    raw = readFileSync(path, 'utf8')
  } catch (err) {
    rmSync(path, { force: true })
    return unreadableResult(asMessage(err))
  }
  rmSync(path, { force: true })

  try {
    const parsed = JSON.parse(raw) as Partial<HomebrewUpgradeResult>
    // A truncated write must surface as a failure, not vanish: the helper is the
    // only witness to what happened while the app was gone.
    if (typeof parsed.ok !== 'boolean') return unreadableResult('the result was incomplete')
    return {
      ok: parsed.ok,
      stage: parsed.stage ?? 'unknown',
      version: parsed.version ?? '',
      detail: parsed.detail ?? ''
    }
  } catch {
    return unreadableResult('the result was not valid JSON')
  }
}

function unreadableResult(detail: string): HomebrewUpgradeResult {
  return {
    ok: false,
    stage: 'result',
    version: '',
    detail: `The update ran but its outcome could not be read — ${detail}.`
  }
}

function asMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err)
}
